### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Dpbm** [devilkiller-ag/Quantum-Circuit-Game-Engine#1]
hello @devilkiller-ag, I've tried to install it, but every time that I try to run:

```python
import qcge
``` 

it raises a `ModuleNotFoundError: No module named 'qcge'`.

---

It's a setup problem? or maybe is something with my environment ? 
I've tried several times with different python environments, and all has shown the same problem.

**Comment by ashmitjsg** [comment]
Solved by PR #2

**Comment by ashmitjsg** [comment]
Hi @Dpbm, Thanks for mentioning the issue and rectifying it. ✨ I am excited to see what you are building with QCGE. Do share your project in the Discussions Section of this repository and in the QCGE channel on my discord server: https://discord.com/invite/HfZ4bTbhB2
